version: '3.4'

services:
  api:
    build:
      context: src/BasicEshopCrud.Api
      dockerfile: Dockerfile
      target: base
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - "5001:5001"
    networks:
      - local

networks:
  local:
    name: basic-eshop-crud-network-only_local